version: "3"

services:
  v2ray:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "10150:10150"
    volumes:
      - ./v2ray/config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/

  caddy: 
    image: caddy
    restart: always
    ports:
      - "11310:11310"
    volumes:
      - ./caddy/config/:/etc/caddy/

  subconverter:
    image: tindy2013/subconverter:0.9.0
    restart: always

  subscriber:
    image: benny-subscriber
    restart: always
    ports:
      - "29002:29002"
